enum PartOfSpeech {
  Noun
  Verb
  Adjective
  Adverb
}

type Vocab {
  word: String!
  partOfSpeech: PartOfSpeech!
  definition: String!
  examples: [String!]
  synonyms: [String!]
  antonyms: [String!]
}


type Query {
  allVocabs: [Vocab!]
  findVocabsByWord(word: String!): [Vocab!] @index
}

