micronaut:
  application:
    name: vocab-mate

urban-dict:
  url: https://mashape-community-urban-dictionary.p.rapidapi.com
  api-key-header: X-Rapidapi-Key

words-api:
  url: https://wordsapiv1.p.rapidapi.com
  key-header: X-Rapidapi-Key

