micronaut:
  application:
    name: vocab-mate

rapid-api:
  api-key-header: X-Rapidapi-Key
  api-key: <changeme>
  urban-dict-url: https://mashape-community-urban-dictionary.p.rapidapi.comó
  words-api-url: https://wordsapiv1.p.rapidapi.com
