name: wrangler-build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: workers/vocab-mate
      - name: wrangler build
        uses: alank976/wrangler-action-for-rust@1.0.0
        with: 
          workingDirectory: workers/vocab-mate
          apiToken: foo
          publish: false
          preCommands: wrangler build
